[build]
builder = "NIXPACKS"
buildCommand = "cd backend && python -m pip install --upgrade pip && python -m pip install -r requirements.txt"

[deploy]
startCommand = "cd backend && python -m gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --access-logfile - --error-logfile - app:app"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
