[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --access-logfile - --error-logfile - app:app"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
